package jakarta.tutorial.taskcreator;

import java.util.Set;

import jakarta.ws.rs.ApplicationPath;
import jakarta.ws.rs.core.Application;

/* This class configures JAX-RS for this application.
 * The JAX-RS paths for this application's endpoints are under /jaxrs/ */
@ApplicationPath("/jaxrs/") public class JAXRSApplication extends Application {

    @Override public Set<Class<?>> getClasses() {
        Set<Class<?>> resources = new java.util.HashSet<>();
        addRestResourceClasses(resources);
        return resources;
    }

    /**
     * Do not modify addRestResourceClasses() method. It is automatically re-generated by NetBeans
     * REST support to populate given list with all resources defined in the project.
     */
    private void addRestResourceClasses(Set<Class<?>> resources) {
        resources.add(jakarta.tutorial.taskcreator.TaskEJB.class);
    }

}
